import numpy as ny
import sys
import operator


f1=open(sys.argv[1],"r")
parte=f1.read()

a=parte.count('a')
b=parte.count('b')
c=parte.count('c')
d=parte.count('d')
e=parte.count('e')
f=parte.count('f')
g=parte.count('g')
h=parte.count('h')
i=parte.count('i')
j=parte.count('j')
k=parte.count('k')
l=parte.count('l')
m=parte.count('m')
n=parte.count('n')
o=parte.count('o')
p=parte.count('p')
q=parte.count('q')
r=parte.count('r')
s=parte.count('s')
t=parte.count('t')
u=parte.count('u')
v=parte.count('v')
w=parte.count('w')
x=parte.count('x')
y=parte.count('y')
z=parte.count('z')
cero=parte.count('0')
uno=parte.count('1')
dos=parte.count('2')
tres=parte.count('3')
cuatro=parte.count('4')
cinco=parte.count('5')
seis=parte.count('6')
siete=parte.count('7')
ocho=parte.count('8')
nueve=parte.count('9')
todo=a+b+c+d+e+f+g+h+i+j+k+l+m+n+o+p+q+r+s+t+u+v+w+x+y+z+cero+uno+dos+tres+cuatro+cinco+seis+siete+ocho+nueve

ap=(float(a)/float(todo))
bp=(float(b)/float(todo))
cp=(float(c)/float(todo))
dp=(float(d)/float(todo))
ep=(float(e)/float(todo))
fp=(float(f)/float(todo))
gp=(float(g)/float(todo))
hp=(float(h)/float(todo))
ip=(float(i)/float(todo))
jp=(float(j)/float(todo))
kp=(float(k)/float(todo))
lp=(float(l)/float(todo))
mp=(float(m)/float(todo))
np=(float(n)/float(todo))
op=(float(o)/float(todo))
pp=(float(p)/float(todo))
qp=(float(q)/float(todo))
rp=(float(r)/float(todo))
sp=(float(s)/float(todo))
tp=(float(t)/float(todo))
up=(float(u)/float(todo))
vp=(float(v)/float(todo))
wp=(float(w)/float(todo))
xp=(float(x)/float(todo))
yp=(float(y)/float(todo))
zp=(float(z)/float(todo))
cerop=(float(cero)/float(todo))
unop=(float(uno)/float(todo))
dosp=(float(dos)/float(todo))
tresp=(float(tres)/float(todo))
cuatrop=(float(cuatro)/float(todo))
cincop=(float(cinco)/float(todo))
seisp=(float(seis)/float(todo))
sietep=(float(siete)/float(todo))
ochop=(float(ocho)/float(todo))
nuevep=(float(nueve)/float(todo))

abc=[ap,bp,cp,dp,ep,fp,gp,hp,ip,jp,kp,lp,mp,np,op,pp,qp,rp,sp,tp,up,vp,wp,xp,yp,zp,cerop,unop,dosp,tresp,cincop,seisp,sietep,ochop,nuevep]

ord=sorted(abc)
log1=ny.log(ord[34])
log2=ny.log(ord[33])
log3=ny.log(ord[32])
log4=ny.log(ord[31])
log5=ny.log(ord[30])
log6=ny.log(ord[29])
log7=ny.log(ord[28])
log8=ny.log(ord[27])
log9=ny.log(ord[26])
log10=ny.log(ord[25])
log11=ny.log(ord[24])
log12=ny.log(ord[23])
log13=ny.log(ord[22])
log14=ny.log(ord[21])
log15=ny.log(ord[20])
log16=ny.log(ord[19])
log17=ny.log(ord[18])
log18=ny.log(ord[17])
log19=ny.log(ord[16])
log20=ny.log(ord[15])

logt=[log1,log2,log3,log4,log5,log6,log7,log8,log9,log10,log11,log12,log13,log14,log15,log16,log17,log18,log19,log20]

logr1=ny.log(1)
logr2=ny.log(2)
logr3=ny.log(3)
logr4=ny.log(4)
logr5=ny.log(5)
logr6=ny.log(6)
logr7=ny.log(7)
logr8=ny.log(8)
logr9=ny.log(9)
logr10=ny.log(10)
logr11=ny.log(11)
logr12=ny.log(12)
logr13=ny.log(13)
logr14=ny.log(14)
logr15=ny.log(15)
logr16=ny.log(16)
logr17=ny.log(17)
logr18=ny.log(18)
logr19=ny.log(19)
logr20=ny.log(20)
logr=[logr1,logr2,logr3,logr4,logr5,logr6,logr7,logr8,logr9,logr10,logr11,logr12,logr13,logr14,logr15,logr16,logr17,logr18,logr19,logr20]
m=ny.polyfit(logt,logr,1)


print m[0]

